### ISSUE TITLE
Watch not working with node-sass-glob-importer on CLI

### ISSUE THREAD

**Issue by aripekkako** [maoberlehner/node-sass-magic-importer#150]
Hi,

### Description

Watch is not picking up changes in partials, when using the importer from CLI, i.e. `node-sass --importer ./node_modules/node-sass-glob-importer/dist/cli.js`.

I suspect the reason has something to do with node-graph not being able to build the dependency graph from the globs.

### Package versions

```
$ node-sass -v
node-sass	4.5.3	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```

```
─ node-sass-glob-importer@5.0.0-alpha.15
```

### Steps to reproduce

Add the following scripts to you package.json:

```
    "build-css": "node-sass --importer ./node_modules/node-sass-glob-importer/dist/cli.js src/styles/ -o src/styles/",
    "watch-css": "npm run build-css && npm run build-css -- --watch --recursive"
```

Create folder `src/styles` and create a file called `main.scss` with the content

``` 
@import 'partials/*.scss';
```

Create folder `src/styles/partials` and create a file called `_partial.scss`.

Make changes to `main.scss`. CSS is rebuilt. 

Make changes to `_partial.scss`. CSS rebuild does not happen.

**Comment by maoberlehner** [comment]
Oh, thats a hard one. I'll see what I can do, but it might be that this is impossible to solve.

I'll look into this the following days and will keep you updated.

Thank you for reporting this issue.

**Comment by aripekkako** [comment]
Thank you for the incredibly quick response! 

Is the CLI what make this impossible? I understood from some of the past issues that the importer does in some cases work properly with watch.

**Comment by maoberlehner** [comment]
I'm not quite sure yet, I have to take a closer look to give a definitiv answer, but it might be, that it works in some circumstances, but not in others.

**Comment by maoberlehner** [comment]
Ok, so node-sass watch mode can't detect changes in files imported using a syntax which node-sass does not understand by default. It is possible that it worked some time ago, what I've seen while researching about the watch mode is, that there were quit some changes to the node-sass watch mode behavior.

So I'd recommend to use either Gulp, Grunt, webpack or something similar or https://github.com/kimmobrunfeldt/chokidar-cli

Example: `chokidar 'src/**/*.scss' -c 'npm run build-css'`

**Comment by aripekkako** [comment]
Thank you for the awesome support! 

We're using [Create React App](https://github.com/facebookincubator/create-react-app), which has it's own webpack configuration that cannot be changed easily without ejecting (= losing all future changes to tooling). That's why we were stuck with CLI in the first place. 

`chokidar 'src/**/*.scss' -c 'npm run build-css'` works like a charm and seems to be performant enough. I was worried that build time would grow as I was not sure how well it would be able to optimize the build process.

I will now close this issue.
