### ISSUE TITLE
Error: Cannot find module 'css-selector-extract'

### ISSUE THREAD

**Issue by SethTompkins** [maoberlehner/node-sass-magic-importer#152]
When using this package as an importer via the cli, getting an error that the `css-selector-extract` package cannot be found. It exists in my `node_modules/` directory however.

**Comment by maoberlehner** [comment]
I'm sorry, this was a problem with the latest release of css-selector-extract, please install the package again and make sure the latest release of css-selector-extract (3.3.3) is installed afterwards.
