### ISSUE TITLE
Issues with Node 8 and old node-sass

### ISSUE THREAD

**Issue by elclanrs** [maoberlehner/node-sass-magic-importer#156]
When installing in Node 8 with npm 5.5.1 it needs to compile node-sass@3.13.1 every time because this version didn't support Node 8 and the pre-compiled binary doesn't exist.

I looked into your package.json, and I could see why this version ic coming in through this package. Doing a search in node_modules after install `node-sass-magic-importer` gives me this:

```
λ find node_modules -type d -name 'node-sass'
node_modules/node-sass
node_modules/node-sass-selector-importer/node_modules/node-sass
```

If you inspect the node-sass bundled with `node-sass-selector-importer` it is version 3.13.1.

How is this package ending up there? How can we upgrade this package to the latest node-sass that works in Node 8 with pre-compiled binary?

**Comment by maoberlehner** [comment]
Are you sure that you're using the latest release (5.x.x) of `node-sass-magic-importer`?

The 4.x.x release of this package had `node-sass-selector-importer` as a dependency, and the old 4.x.x release of `node-sass-selector-importer` had `node-sass` 3.13.1 as a dependency.

Please update `node-sass-magic-importer` to the latest 5.x.x release and everything should be fine.

Thank you for using `node-sass-magic-importer`.

**Comment by elclanrs** [comment]
Ah, thanks that was it!
