### ISSUE TITLE
Globbing :: Error when directory is empty

### ISSUE THREAD

**Issue by Sebastian-Fitzner** [maoberlehner/node-sass-magic-importer#161]
Hi, 

I found an issue when working with empty directories. My current setup looks like that: 

**SCSS File**
``` scss
/* ===================================================
Main File For Imports
=================================================== */
// Global Variables and Settings
@import "shared/styles/shared";

// Icons
@import "shared/styles/icons/**/*.scss";
``` 

**Task Configuration**
The configuration is untouched and the module is used via Webpacks `sass-loader`. 

**Error** 
When I have no file in that `icons` directory, the module throws an error and stops at going any further: 

``` bash
File to import not found or unreadable: shared/styles/icons/**/*.scss.
```

BTW: The icon files are generated by some specific tasks, means in the beginning of a project this directory is empty. 

**Improvement**
When no file is found, log an info message and skip the import string instead of throwing an error. 

I can even try to create a pull request, if you want to. 
Greets

**Comment by maoberlehner** [comment]
Hi @Sebastian-Fitzner 

Thank you for the detailed issue report.
Although this is the "intended" behavior, you're absolutely right, that it is not the most convenient way of handling empty directories.
I'll look into this.
