### ISSUE TITLE
Update to node-sass v4.9 due to Node v10

### ISSUE THREAD

**Issue by mattsoltani** [maoberlehner/node-sass-magic-importer#169]
With the recent release of node v10, node-sass was broken (see https://github.com/sass/node-sass/issues/2345) including node-sass-magic-importer. 
This has been fixed in the v4.9 release, so node-sass-magic-importer just needs to be updated to use this version to get the fix.

**Comment by maoberlehner** [comment]
Thanks for reporting this!

**Comment by mattsoltani** [comment]
@maoberlehner Thank you for fixing this already. It doesn't seem to be released yet. When do you expect to release the update?

**Comment by maoberlehner** [comment]
Hey @mattsoltani, I've just published a new release, but I don't think this should have any effect on you. `node-sass` was only a `devDependency` of the Monorepo, so the `node-sass-magic-importer` package does not (explicitly) depend on any specific version of `node-sass` (as you can see here: https://github.com/maoberlehner/node-sass-magic-importer/blob/master/packages/node-sass-magic-importer/package.json).
