### ISSUE TITLE
node-sass-once-importer does not create a new store per importer

### ISSUE THREAD

**Issue by ychailler** [maoberlehner/node-sass-magic-importer#189]
The context `nodeSassOnceImporterContext` created in each importer refers to the same store created in the `contextTemplate` object. 
When using webpack-dev-server and the watch feature, the resulted file generated after the first code modification become empty as all imports are already stored in the store.

The behaviour is different from the node-sass-magic-importer where the store is created for each importer. In that case it works fine

**Comment by maoberlehner** [comment]
Do I understand this correctly that `node-sass-once-importer` does not work but `node-sass-magic-importer` does work correctly?

**Comment by ychailler** [comment]
no it is the opposite: it works with `node-sass-magic-importer` but not with `node-sass-once-importer`

**Comment by maoberlehner** [comment]
That's exactly what i wrote 😅

I'll take a look into it. Thanks for reporting.

**Comment by maoberlehner** [comment]
`node-sass-once-importer@5.3.1` should work as expected. Thanks again for reporting this :)
