### ISSUE TITLE
[node-sass-glob-importer] Webpack Dev Server don't watch edited imported files using globbing

### ISSUE THREAD

**Issue by mperu92** [maoberlehner/node-sass-magic-importer#196]
When i edit my  `.scss` file imported through `main.scss`, `webpack-dev-server` doesn't watch editing.

This is config on `webpack.config.dev.js`:
```es6
const globImporter = require('node-sass-glob-importer');

/// ...

{
    test: /\.s[c|a]ss$/,
    use: [
        { 
            loader: 'css-loader', 
            options: { 
                sourceMap: true,
                importLoaders: 3,
            } 
        },
        {
            loader: 'postcss-loader',
            options: {
                ident: 'postcss',
                sourceMap: true,
                plugins: [
                    require('autoprefixer')({
                        grid: true,
                        remove: true,
                    }),
                    require('postcss-flexbugs-fixes'),
                ]
            }
        },
        {
            loader: 'sass-loader',
            options: {
                sourceMap: true,
                importer: globImporter()
            }
        }
    ]
},

/// ...
```
import in the `main.scss`:

```scss
@import "/core/utility/*.scss";

// ...
```
but files inside `utility` folder are not beign watched by `webpack-dev-server` .
Does anyone know what the problem might be?

**Comment by maoberlehner** [comment]
Duplicate of https://github.com/maoberlehner/node-sass-magic-importer/issues/178

See: https://github.com/maoberlehner/node-sass-magic-importer/issues/178#issuecomment-424271452

**Comment by mperu92** [comment]
> EDIT: Just realized this is not a duplicate of #178
> 
> Usually this should work with webpack. Config looks fine-

Thanks,
while I wait if someone can give me more informations, I continue to do tests.
If I can unlock the situation I'll let you know!

**Comment by mperu92** [comment]
Issue solved itself, after restarting devServer now seems reading gobbed files
