### ISSUE TITLE
check if it is possible to add source map support (show correct line numbers)

### ISSUE THREAD

**Issue by maoberlehner** [maoberlehner/node-sass-magic-importer#22]

**Comment by rafegoldberg** [comment]
oh word, does that mean source maps work in ef18161? (glanced thru the commit diff src, but didn't glean much from it tbh!) anyway, I've witnessed this issue first hand, and it's the only thing holding me back from using this plugin for everything. would be great to hear it worked. Either way, much obliged family for your work on this!

**Comment by rafegoldberg** [comment]
also, more generally, any tips for getting source maps to work any better? anything to avoid? or is it all a fools errand?

**Comment by maoberlehner** [comment]
Hmm, you're right, this commit doesn't do anything with source maps – maybe I referenced the wrong issue number in this commit, sorry, reopen this.

Things that should work without any problems:
- Glob importing
- Once importing
- Package importing

That leaves us with:
- Selector importing
- Node importing

With selector importing and node importing, the referenced file in the sourcemap is correct, but lines get mixed up.

Im currently looking into it, if it is possible to pass through a sourcemap generated by PostCSS to node-sass, if this is possible, expect a fix in the following days, if this is not possible, there may never be a fix for this problem.

**Comment by maoberlehner** [comment]
Ok, so apparently it is not possible to pass an existing sourcemap to node-sass. But I have an idea.

Currently (S)CSS nodes which do not match the specified selector or node filter, are removed completely – thats why the lines do not match anymore in the sourcemap – but I could change this behaviour to instead of removing them, replacing nodes with comments

```scss
.some-class {
   ...
}

// preserve line
// preserve line
// preserve line

.another-class {
   ...
}
```

Where you can see the `// preserve line` comments, would've been a class which was not imported with selector importing. So line numbers stay intact but there are now comments in the code... Usually this shouldn't be a problem, because node-sass removes single line comments but it's not the most elegant solution.

And you'd often times end up with empty atrules.

```scss
@media (min-width: 42em) {
// preserve line
// preserve line
// preserve line
}
```

Not the end of the world if you're using a minifier which is stripping those, but still, not exactly elegant.

Would you be interested in beta testing such a solution?

**Comment by rafegoldberg** [comment]
Yeah absolutely! Let me know.

**Comment by maoberlehner** [comment]
@rafegoldberg I just published `5.0.0-alpha.11` which should have 100% source map support :)

I've updated the dependencies responsible for extracting nodes and selectors (https://github.com/maoberlehner/css-node-extract, https://github.com/maoberlehner/css-selector-extract) to make it possible to preserve lines when removing nodes.

I'd be happy if you could test the new release with your code. So far everything looks fine, but I could imagine, that in some edge cases the handling of empty lines may doesn't work 100%.

**Comment by rafegoldberg** [comment]
@maoberlehner awesome! A bit busy this coming week but will pull down `5.0.0-alpha.11` and test it out when I get a chance. I'll keep ya posted.

**Comment by rafegoldberg** [comment]
@maoberlehner just took `5.0.0-alpha.12` out for a spin and from my (admittedly brief) testing it seems to work swimmingly. par example:

![image](https://user-images.githubusercontent.com/886627/30838185-eebc1478-a21e-11e7-8cd7-bfcbda064929.png)

Which is indeed mapped from the _correct_ Sass source file, on the _correct_ line!

![image](https://user-images.githubusercontent.com/886627/30838241-3050d004-a21f-11e7-9e90-c892b4eb7815.png).

Will be relying more heavily on this package in the near future and will update ya further if I come across other issues. The quick moves on this ticket are v. appreciated!
