### ISSUE TITLE
CSS import issue

### ISSUE THREAD

**Issue by lordgiotto** [maoberlehner/node-sass-magic-importer#91]
Hi,
first of all thanks for this importer, it's really awesome! 😄 

I've noticed an annoying bug related to css imports.

These are the steps to reproduce the bug:

If I want to import a css from a node module I can specify the full path and omit the extension:

```scss
@import "../node_modules/owl.carousel/dist/assets/owl.carousel";
``` 
_(this works)_

But if i add the extension or I try to use the ~ notation
```scss
@import "../node_modules/owl.carousel/dist/assets/owl.carousel.css";
``` 
```scss
@import "~owl.carousel/dist/assets/owl.carousel";
``` 
```scss
@import "~owl.carousel/dist/assets/owl.carousel.css";
``` 

the compiled result is the following:

```css
@import url(/Users/name/project/node_modules/owl.carousel/dist/assets/owl.carousel.css);
``` 

It's an expected behaviour or it could be fixed?

Thank you very much!

**Comment by maoberlehner** [comment]
Thank you for your kind words and for reporting this bug – I will look into this the following days.

**Comment by maoberlehner** [comment]
The latest release (4.1.2) should fix the problem. Please update the package and let me know if something still doesn't work as expected.

**Comment by webmarkelov** [comment]
I have a trouble with ```node-sass-magic-importer@5.0.0-alpha.14``` version too
```scss
// before
@import '~normalize.css';

// after
@import url(/.../node_modules/normalize.css/normalize.css);
```

**Comment by maoberlehner** [comment]
@webmarkelov thank you for reporting this problem, I'm looking into this.

**Comment by maoberlehner** [comment]
@webmarkelov ok so this is a little bit of a gray area and there is no ideal way of handling such a situation. What this importer does, if it encounters an URL starting with `~`, is to resolve the path to the packages main file and let node-sass do with it whatever it wants.

When node-sass encounters a file with `.css` ending, it creates the `url()` import string you've posted. So basically everything works as intended. But I agree, that this is not the result one is expecting when importing a CSS file from an npm package.

In the earlier release I fixed this with a workaround – I guess I have to do the same in v5 again.

Thanks for reminding me of this issue. I'll fix this in the next couple of days. Please use v4 in the meantime if you're relying on this functionality (or switch to https://github.com/JohnAlbin/normalize-scss).

Thanks for using node-sass-magic-importer

**Comment by demurgos** [comment]
Hi,
I am using `node-sass-magic-importer` version `5.0.0-alpha.14`.
I am trying to inline a CSS style from [highlight.js](https://github.com/isagalaev/highlight.js/tree/master/src/styles).
According to my research, to inline a file I need to provide its path without the `.css` extension, unfortunately this does not work with the `~` syntax:

```
// This properly inlines default.css, but is terrible to maintain
@import "../../../../node_modules/highlight.js/styles/default";
```

```
// This yields an error
@import "~highlight.js/styles/default";
```

Here is the error:
```
Error: File to import not found or unreadable: ~highlight.js/styles/default.
Parent style sheet: /data/projects/blog/themes/domu/source/styles/main.scss
ERROR Asset render failed: styles/main.css
Error: File to import not found or unreadable: ~highlight.js/styles/default.
Parent style sheet: /data/projects/blog/themes/domu/source/styles/main.scss
    at options.error (/data/projects/blog/node_modules/node-sass/lib/index.js:291:26)
```

I previously had a similar error for `normalize.css` but your workaround (using `normalize-scss`) solved it (and is in fact superior). But now, with highlight.js, I am stuck.

**Comment by maoberlehner** [comment]
I'm on it. I've already thought about a solution for this problem but hesitated to implement it yet, because it's a little bit hack, but I can see how this is an important feature for many people so I'm going to implement this soon™
